name: Main Pipeline

env:
    HUSKY: 0

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    dependency-review:
        uses: ./.github/workflows/dependency-review.yml

    code-quality:
        uses: ./.github/workflows/code-quality.yml
